### ISSUE TITLE
Long loading times

### ISSUE THREAD

**Issue by SnakyLeVrai** [SirDiazo/AGExt#31]
Hi,

I've installed AGX on my long-ago-started science carreer (1.0.4) and KSP would just freeze on the black loading screen, when loading the save from the main menu (when launching KSP, not from within a game).

1- First workaround was either to create a new game (science, career or sandbox, doesn't matter), then quitting the new game ("quit to main menu"), then loading my save.
2- Second workaround was to load another game: I had a sandbox game with no flight in it (just a brand new sandbox career in which I've never played), then go back to main menu, then load my science career and everything was fine.

Then I decided to go and clean old savegames in my science career folder, removed 2Gb worth of obsolete saves and a TON of old AGX files. I only kept those of today. Game would load directly without freezing - confirmed it several times. However it takes quite some time to load - a good 30-40sec maybe.

In the end, I think the game was never actually frozen/crashed, it was just rummaging through the nearly 300 AGX files in the folder. After cleaning up, there were 3 AGExt00xxx.cfg files left (~380kb each, today files - looks like I hit F5 3 times today ...), which could explain why it takes so long.

Maybe an automatic clean up procedure is required here?

Anyway - this mod kicks ass, I've been dreaming of one of those for a looong time :D

**Comment by SirDiazo** [comment]
I think this is working as intended. It is actually the clean up routine that is causing the delay.

AGX keeps one of its save files around for every .sfs file in the directory. You mention cleaning up a lot of old .sfs files so AGX would get rid of the associated AGX save file on the next startup of KSP (if you didn't delete them manually already).

To maintain consistency across saves, AGX must use a separate AGX file for each .sfs file so when the cleanup routine runs, AGX has to open each .sfs file in your save directory to see which AGX file belongs to that save file so it knows which files to keep.

Due to how Squad programmed the ConfigNode system used to save the .sfs files, it is extremely slow to open .sfs files like this and it does not take long for a .sfs backup utility (such as the one bundled with KAC) to generate enough .sfs files that it imposes a noticeable delay on loading as you have witnessed. 

Because of this, I write a time stamp to the log at the start and end of the clean up routine so you can see how much time is caused by this issue vs. how much is just the time KSP needs to load.

If you are okay with manually cleaning your files up, you can go to the GameData\Diazo\AGExt\AGExt.cfg file and change the "DeleteOldSaves" value from 1 to 0, this will stop the clean up routine from running but will leave behind old AGX save files that are no longer used until you delete them manually from the saves folder.

**Comment by SnakyLeVrai** [comment]
Ok I understand now. I'll keep the settings the way they are, that'll avoid mistakes.

Thanks for the explanation and the tips!

**Comment by SirDiazo** [comment]
This issue is rendered moot as version 1.34 and newer no longer use external files and so this clean up routine is no longer run.
