### ISSUE TITLE
AGExt blocks functionality of CameraFocusChanger v1.0.0

### ISSUE THREAD

**Issue by LeLeon** [SirDiazo/AGExt#33]
After comparison with other players dll list in the CameraFocusChanger thread, i tracked the problem to AGExt. Perhaps it's a setting?

Edit: I'm absolutely sure, i used both back in 1.1.2

Edit 2:
I changed in file "AGExt.settings"

from:

LockOutKSPManager = 1

to

LockOutKSPManager = 0

Does this bring any known issues to AGExt or other mods? What is this config line made for?

**Comment by SirDiazo** [comment]
There a discussion already started on this issue you could link me to? AGX does not touch anything camera related so I'm puzzled by this.

What the LockOutKSPManager line does is control if stock KSP ignores the activation of custom action groups 1 through 10.

When LockOutKSPManager = 1, when you go to flight mode AGX locks the custom action groups through the InputLockManager class so that when you press the 1 key, KSP ignores it and does not try to activate group 1. AGX also sees the 1 key get pressed and then activates group 1 so the player sees the expected behavior.

When LockOutKSPManager = 0, AGX does not lock the custom action groups. So when the 1 key is pressed, stock KSP does try to activate group 1, then AGX `also` activates group 1 so if there are any toggle type actions in the group the player sees unexpected behavior. 

Almost all players should leave this set to 1, a few players using control pads/joysticks will need to set it to 0 and then mess with KSP's stock keybindings to prevent the double activation.

**Comment by LeLeon** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/122491-12-camera-focus-changer-v100/&page=3

Here it starts. 

Thanks for explanation of that setting. So, when i use "DefaultActionGroups" mod, who always set solar panel toggle on "1" and i use AGX "1" to light toggle, always solar panel and light will be toggled when i press "1". So with DAG 1,2 and 0 keys are set with functions. But good for me, that these functions are exactly the key bindings i used with AGX. :)

But why can this lockout option have influence to CFC and blocks it. Are you able to investigate the  disharmony of these mods?

**Comment by SirDiazo** [comment]
Discussion continues here:
https://github.com/zentarul/camerafocuschanger/issues/1
