### ISSUE TITLE
AGExt change fonts of other mods header

### ISSUE THREAD

**Issue by LeLeon** [SirDiazo/AGExt#34]
While trying to find a settings fix for CFC issue i found out, that when i open right click menu in flight the header texts fonts of other open mod windows switch. Closing AGExt right click menu set the fonts back to normal.

http://www2.pic-upload.de/img/32025200/Unbenannt-1.jpg
http://www2.pic-upload.de/img/32025204/Unbenannt-2.jpg

**Comment by SirDiazo** [comment]
This again?

The root cause of this is that KSP does not isolate the GUI class correctly and that all mod GUI windows inherit from in the old UI system. This means that settings can bleed over between mods such as here.

This is the 3rd or 4th time this has come up and as mods migrate to the new UI system it will no longer be an issue.

As the only effect is changing the font I have no plans to spend any time on this when I can be putting that time into transitioning to the new UI system.

**Comment by LeLeon** [comment]
thanks for answer. yeah, just optics for short time, but i never noticed it before. So, no priority.
